//This file is generated by bin/hook.js
var template = require('lodash.template');
module.exports = {

  'overlay_buttons': template('<div class="clappr-overlay-container">  Hello World!</div>'),

  CSS: {
    
      'overlay_buttons': 'div.clappr-overlay-container{font-size:100px;color:#fff;background-color:rgba(134,134,134,.68);position:fixed;z-index:1;width:100%;height:100%;box-shadow:inset 0 0 10px 16px #000;text-shadow:0 0 6px #000}',
    
  }
};
