//This file is generated by bin/hook.js
var template = require('lodash.template');
module.exports = {

  'overlay_buttons': template('<div class="clappr-overlay">  <div class="clappr-overlay-container">    <div class="clappr-overlay-timer">      <div class="label"><span>45</span><small style="font-size:0.5em">s</small></div>      <div class="shadow"></div>      <div class="pie">        <div class="quarter-circle top-right-side"></div>        <div class="quarter-circle bottom-right-side"></div>        <div class="quarter-circle top-left-side"></div>        <div class="quarter-circle bottom-left-side"></div>      </div>    </div>  </div></div><div class="clappr-overlay-fixed"></div>'),

  CSS: {
    
      'overlay_buttons': 'div,span{box-sizing:border-box}div.clappr-overlay{color:#fff;background-color:rgba(134,134,134,.68);position:fixed;z-index:1;width:100%;height:100%;box-shadow:inset 0 0 10px 16px #000;text-shadow:0 0 6px #000;cursor:initial}div.clappr-overlay-container{top:10px;bottom:10px;left:10px;right:10px;width:auto;height:auto;position:fixed;background:rgba(63,63,63,.51)}div.clappr-overlay-timer{font-size:33px;position:fixed;bottom:10px;right:10px;width:2.5em;height:2.5em}div.clappr-overlay-timer .label{width:2.5em;height:2.5em;line-height:2.45em;font-weight:700;text-shadow:#2f2c2b -2px 1px 6px;background:#195819;border-radius:50%;display:inline-block;text-align:center;-webkit-font-smoothing:antialiased}div.clappr-overlay-timer .label span{line-height:2.35em;font-size:.85em}div.clappr-overlay-timer .pie{position:absolute;height:2.4em;width:2.4em;top:.05em;left:.05em}div.clappr-overlay-timer .pie .quarter-circle{position:absolute;height:2.4em;width:2.4em;border:.226em solid #e74c3c;border-radius:50%;clip:rect(-.15em 2.55em 1.16em 1.16em);left:0;top:0}div.clappr-overlay-timer .pie .top-left-side{-webkit-transform:rotate(270deg);transform:rotate(270deg)}div.clappr-overlay-timer .pie .bottom-left-side{-webkit-transform:rotate(180deg);transform:rotate(180deg)}div.clappr-overlay-timer .pie .bottom-right-side{-webkit-transform:rotate(90deg);transform:rotate(90deg)}div.clappr-overlay-timer .pie .top-right-side{-webkit-transform:rotate(0deg);transform:rotate(0deg)}div.clappr-overlay-timer .shadow{width:2.5em;height:2.5em;border:.34em solid #bdc3c7;border-radius:50%;position:absolute;top:0;left:0}',
    
  }
};
